export const INTERNAL_CATEGORIES = ["technology", "marketing", "healthcare", "finance", "engineering", "sales", "design", "education"] as const;

type InternalCategory = (typeof INTERNAL_CATEGORIES)[number];

export const CATEGORY_KEYWORDS: Record<InternalCategory, string[]> = {
	technology: [
		"developer",
		"software",
		"engineer",
		"programmer",
		"frontend",
		"backend",
		"full stack",
		"fullstack",
		"web developer",
		"mobile developer",
		"app developer",
		"ios",
		"android",
		"react",
		"nextjs",
		"vue",
		"angular",
		"node",
		"nodejs",
		"typescript",
		"javascript",
		"python",
		"java",
		"php",
		"golang",
		"ruby",
		"laravel",
		"django",
		"flask",
		"spring",
		".net",
		"c#",
		"c++",
		"data engineer",
		"data scientist",
		"data analyst",
		"ml engineer",
		"ai engineer",
		"machine learning",
		"artificial intelligence",
		"devops",
		"cloud",
		"aws",
		"azure",
		"gcp",
		"kubernetes",
		"docker",
		"sre",
		"site reliability",
		"qa engineer",
		"test engineer",
		"automation tester",
		"cybersecurity",
		"information security",
		"security engineer",
		"blockchain",
		"smart contract",
		"solidity",
		"web3",
	],

	marketing: [
		"marketing",
		"digital marketing",
		"growth",
		"growth marketing",
		"growth hacker",
		"seo",
		"search engine optimization",
		"sem",
		"paid ads",
		"ppc",
		"google ads",
		"facebook ads",
		"social media",
		"social media manager",
		"community manager",
		"content",
		"content creator",
		"content strategist",
		"copywriter",
		"email marketing",
		"crm marketing",
		"brand",
		"brand manager",
		"product marketing",
		"marketing analyst",
		"marketing manager",
	],

	healthcare: [
		"nurse",
		"registered nurse",
		"doctor",
		"physician",
		"medical",
		"healthcare",
		"clinical",
		"clinic",
		"hospital",
		"pharmacist",
		"pharmacy",
		"therapist",
		"physical therapist",
		"occupational therapist",
		"dentist",
		"dental",
		"surgeon",
		"medical assistant",
		"lab technician",
		"laboratory",
		"health worker",
		"health officer",
	],

	finance: [
		"finance",
		"financial",
		"accountant",
		"accounting",
		"auditor",
		"audit",
		"bank",
		"banking",
		"investment",
		"investment analyst",
		"financial analyst",
		"finance manager",
		"portfolio manager",
		"risk analyst",
		"risk manager",
		"credit analyst",
		"trader",
		"trading",
		"tax",
		"tax advisor",
		"payroll",
		"bookkeeper",
		"controller",
		"treasury",
		"fintech",
	],

	engineering: [
		"mechanical",
		"civil",
		"electrical",
		"structural",
		"industrial engineer",
		"manufacturing engineer",
		"process engineer",
		"plant engineer",
		"project engineer",
		"production engineer",
		"chemical engineer",
		"automation engineer",
		"robotics engineer",
		"cad",
		"solidworks",
		"autocad",
	],

	sales: [
		"sales",
		"sales executive",
		"sales manager",
		"sales representative",
		"account executive",
		"account manager",
		"business development",
		"business development manager",
		"bdr",
		"sdr",
		"lead generation",
		"client acquisition",
		"customer acquisition",
		"partnerships",
		"channel sales",
		"territory manager",
	],

	design: [
		"designer",
		"design",
		"ui",
		"ux",
		"ui designer",
		"ux designer",
		"product designer",
		"graphic",
		"graphic designer",
		"visual designer",
		"motion designer",
		"illustrator",
		"brand designer",
		"web designer",
		"figma",
		"adobe xd",
		"sketch",
		"photoshop",
		"after effects",
	],

	education: ["teacher", "tutor", "lecturer", "instructor", "professor", "teaching", "teaching assistant", "educator", "trainer", "training", "curriculum", "academic", "school", "university", "learning specialist", "education consultant"],
};

export function ruleBasedCategorize(title: string, description?: string, industry?: string): InternalCategory | null {
	const text = `${title} ${description || ""} ${industry || ""}`.toLowerCase();

	const scores: Record<InternalCategory, number> = {
		technology: 0,
		marketing: 0,
		healthcare: 0,
		finance: 0,
		engineering: 0,
		sales: 0,
		design: 0,
		education: 0,
	};

	for (const category of INTERNAL_CATEGORIES) {
		for (const keyword of CATEGORY_KEYWORDS[category]) {
			if (text.includes(keyword)) {
				scores[category] += 1;
			}
		}
	}

	let bestCategory: InternalCategory | null = null;
	let maxScore = 0;

	for (const category of INTERNAL_CATEGORIES) {
		if (scores[category] > maxScore) {
			maxScore = scores[category];
			bestCategory = category;
		}
	}

	return maxScore > 0 ? bestCategory : null;
}
